import 'package:material_ui/material_ui.dart';

import 'kor_palette.dart';

/// Kor [ColorScheme]s with every Material 3 role set by hand (no `fromSeed`),
/// so light/dark stay consistent and the contrast ratios in
/// `docs/design/kor-design-proposal.md` §3.1 hold.
///
/// Roles the design doc does not specify are derived and documented inline:
/// - `secondary*` mirrors `primary*`: Kor has a single accent colour.
/// - `*Fixed` roles reuse the light container/on-container pairs.
/// - `surfaceTint` is transparent: surfaces are opaque warm neutrals and
///   elevation is expressed with `surfaceContainer*` steps and shadows.
/// - `surfaceContainerHighest`, `surfaceDim` and `surfaceBright` extend the
///   documented `surfaceContainer*` ramp by one step.
abstract final class KorColorScheme {
  static const ColorScheme light = ColorScheme(
    brightness: Brightness.light,
    primary: KorPaletteLight.primary,
    onPrimary: KorPaletteLight.onPrimary,
    primaryContainer: KorPaletteLight.primaryContainer,
    onPrimaryContainer: KorPaletteLight.onPrimaryContainer,
    primaryFixed: KorPaletteLight.primaryContainer,
    primaryFixedDim: KorPaletteLight.inversePrimary,
    onPrimaryFixed: KorPaletteLight.onPrimaryContainer,
    onPrimaryFixedVariant: KorPaletteDark.primaryContainer,
    secondary: KorPaletteLight.primary,
    onSecondary: KorPaletteLight.onPrimary,
    secondaryContainer: KorPaletteLight.primaryContainer,
    onSecondaryContainer: KorPaletteLight.onPrimaryContainer,
    secondaryFixed: KorPaletteLight.primaryContainer,
    secondaryFixedDim: KorPaletteLight.inversePrimary,
    onSecondaryFixed: KorPaletteLight.onPrimaryContainer,
    onSecondaryFixedVariant: KorPaletteDark.primaryContainer,
    tertiary: KorPaletteLight.tertiary,
    onTertiary: KorPaletteLight.onTertiary,
    tertiaryContainer: KorPaletteLight.tertiaryContainer,
    onTertiaryContainer: KorPaletteLight.onTertiaryContainer,
    tertiaryFixed: KorPaletteLight.tertiaryContainer,
    tertiaryFixedDim: KorPaletteDark.tertiary,
    onTertiaryFixed: KorPaletteLight.onTertiaryContainer,
    onTertiaryFixedVariant: KorPaletteDark.tertiaryContainer,
    error: KorPaletteLight.error,
    onError: KorPaletteLight.onError,
    errorContainer: KorPaletteLight.errorContainer,
    onErrorContainer: KorPaletteLight.onErrorContainer,
    surface: KorPaletteLight.surface,
    onSurface: KorPaletteLight.onSurface,
    onSurfaceVariant: KorPaletteLight.onSurfaceVariant,
    surfaceDim: Color(0xFFE4DDD1),
    surfaceBright: KorPaletteLight.surface,
    surfaceContainerLowest: KorPaletteLight.surfaceContainerLowest,
    surfaceContainerLow: KorPaletteLight.surfaceContainerLow,
    surfaceContainer: KorPaletteLight.surfaceContainer,
    surfaceContainerHigh: KorPaletteLight.surfaceContainerHigh,
    surfaceContainerHighest: Color(0xFFE4DDD1),
    outline: KorPaletteLight.outline,
    outlineVariant: KorPaletteLight.outlineVariant,
    shadow: KorPaletteLight.shadow,
    scrim: KorPaletteLight.scrim,
    inverseSurface: KorPaletteLight.inverseSurface,
    onInverseSurface: KorPaletteLight.onInverseSurface,
    inversePrimary: KorPaletteLight.inversePrimary,
    surfaceTint: Color(0x00000000),
  );

  static const ColorScheme dark = ColorScheme(
    brightness: Brightness.dark,
    primary: KorPaletteDark.primary,
    onPrimary: KorPaletteDark.onPrimary,
    primaryContainer: KorPaletteDark.primaryContainer,
    onPrimaryContainer: KorPaletteDark.onPrimaryContainer,
    primaryFixed: KorPaletteLight.primaryContainer,
    primaryFixedDim: KorPaletteDark.primary,
    onPrimaryFixed: KorPaletteLight.onPrimaryContainer,
    onPrimaryFixedVariant: KorPaletteDark.primaryContainer,
    secondary: KorPaletteDark.primary,
    onSecondary: KorPaletteDark.onPrimary,
    secondaryContainer: KorPaletteDark.primaryContainer,
    onSecondaryContainer: KorPaletteDark.onPrimaryContainer,
    secondaryFixed: KorPaletteLight.primaryContainer,
    secondaryFixedDim: KorPaletteDark.primary,
    onSecondaryFixed: KorPaletteLight.onPrimaryContainer,
    onSecondaryFixedVariant: KorPaletteDark.primaryContainer,
    tertiary: KorPaletteDark.tertiary,
    onTertiary: KorPaletteDark.onTertiary,
    tertiaryContainer: KorPaletteDark.tertiaryContainer,
    onTertiaryContainer: KorPaletteDark.onTertiaryContainer,
    tertiaryFixed: KorPaletteLight.tertiaryContainer,
    tertiaryFixedDim: KorPaletteDark.tertiary,
    onTertiaryFixed: KorPaletteLight.onTertiaryContainer,
    onTertiaryFixedVariant: KorPaletteDark.tertiaryContainer,
    error: KorPaletteDark.error,
    onError: KorPaletteDark.onError,
    errorContainer: KorPaletteDark.errorContainer,
    onErrorContainer: KorPaletteDark.onErrorContainer,
    surface: KorPaletteDark.surface,
    onSurface: KorPaletteDark.onSurface,
    onSurfaceVariant: KorPaletteDark.onSurfaceVariant,
    surfaceDim: KorPaletteDark.background,
    surfaceBright: Color(0xFF3D3831),
    surfaceContainerLowest: KorPaletteDark.surfaceContainerLowest,
    surfaceContainerLow: KorPaletteDark.surfaceContainerLow,
    surfaceContainer: KorPaletteDark.surfaceContainer,
    surfaceContainerHigh: KorPaletteDark.surfaceContainerHigh,
    surfaceContainerHighest: Color(0xFF3D3831),
    outline: KorPaletteDark.outline,
    outlineVariant: KorPaletteDark.outlineVariant,
    shadow: KorPaletteDark.shadow,
    scrim: KorPaletteDark.scrim,
    inverseSurface: KorPaletteDark.inverseSurface,
    onInverseSurface: KorPaletteDark.onInverseSurface,
    inversePrimary: KorPaletteDark.inversePrimary,
    surfaceTint: Color(0x00000000),
  );
}
