// Tables mix const-able and DateTime rows; keep them uniform.
// ignore_for_file: prefer_const_constructors

import 'capture_case.dart';

/// Day phrases, weekdays, month days and relative dates.
/// Clock: Pazar 13 Eylül 2026 14:32.
final dateCases = <CaptureCase>[
  // bugün / yarın / öbür gün
  CaptureCase('yarın ekmek al',
      title: 'Ekmek al', at: DateTime(2026, 9, 14), tokens: ['date:yarın']),
  CaptureCase('Yarın ekmek al',
      title: 'Ekmek al', at: DateTime(2026, 9, 14), tokens: ['date:Yarın']),
  CaptureCase('YARIN ekmek al',
      title: 'Ekmek al', at: DateTime(2026, 9, 14), tokens: ['date:YARIN']),
  CaptureCase('ekmek al yarın',
      title: 'Ekmek al', at: DateTime(2026, 9, 14), tokens: ['date:yarın']),
  CaptureCase('yarin ekmek al',
      title: 'Ekmek al', at: DateTime(2026, 9, 14), tokens: ['date:yarin']),
  CaptureCase('bugün faturayı öde',
      title: 'Faturayı öde', at: DateTime(2026, 9, 13), tokens: ['date:bugün']),
  CaptureCase('bugun faturayi ode',
      title: 'Faturayi ode', at: DateTime(2026, 9, 13), tokens: ['date:bugun']),
  CaptureCase('öbür gün kargoyu al',
      title: 'Kargoyu al',
      at: DateTime(2026, 9, 15),
      tokens: ['date:öbür gün']),
  CaptureCase('öbürgün kargoyu al',
      title: 'Kargoyu al', at: DateTime(2026, 9, 15), tokens: ['date:öbürgün']),
  CaptureCase('obur gun kargoyu al',
      title: 'Kargoyu al',
      at: DateTime(2026, 9, 15),
      tokens: ['date:obur gun']),
  CaptureCase('yarına kadar formu doldur',
      title: 'Formu doldur',
      at: DateTime(2026, 9, 14),
      tokens: ['date:yarına kadar']),
  CaptureCase('yarınki toplantı notları', title: 'Yarınki toplantı notları'),
  CaptureCase('bugünkü işleri bitir', title: 'Bugünkü işleri bitir'),
  CaptureCase('yarın, bugün değil',
      title: 'Bugün değil', at: DateTime(2026, 9, 14), tokens: ['date:yarın']),

  // haftaya / gelecek hafta
  CaptureCase('haftaya dişçi randevusu',
      title: 'Dişçi randevusu',
      at: DateTime(2026, 9, 20),
      tokens: ['date:haftaya']),
  CaptureCase('haftaya cuma sunum',
      title: 'Sunum', at: DateTime(2026, 9, 25), tokens: ['date:haftaya cuma']),
  CaptureCase('haftaya bugün kira',
      title: 'Kira', at: DateTime(2026, 9, 20), tokens: ['date:haftaya bugün']),
  CaptureCase('gelecek hafta tatil planı',
      title: 'Tatil planı',
      at: DateTime(2026, 9, 20),
      tokens: ['date:gelecek hafta']),
  CaptureCase('önümüzdeki hafta pazartesi toplantı',
      title: 'Toplantı',
      at: DateTime(2026, 9, 21),
      tokens: ['date:önümüzdeki hafta pazartesi']),
  CaptureCase('gelecek çarşamba veli toplantısı',
      title: 'Veli toplantısı',
      at: DateTime(2026, 9, 16),
      tokens: ['date:gelecek çarşamba']),

  // weekdays
  CaptureCase('pazartesi spor',
      title: 'Spor', at: DateTime(2026, 9, 14), tokens: ['date:pazartesi']),
  CaptureCase('PAZARTESİ spor',
      title: 'Spor', at: DateTime(2026, 9, 14), tokens: ['date:PAZARTESİ']),
  CaptureCase('PAZARTESI spor',
      title: 'Spor', at: DateTime(2026, 9, 14), tokens: ['date:PAZARTESI']),
  CaptureCase('salı spor',
      title: 'Spor', at: DateTime(2026, 9, 15), tokens: ['date:salı']),
  CaptureCase('sali spor',
      title: 'Spor', at: DateTime(2026, 9, 15), tokens: ['date:sali']),
  CaptureCase('çarşamba toplantı',
      title: 'Toplantı', at: DateTime(2026, 9, 16), tokens: ['date:çarşamba']),
  CaptureCase('carsamba toplanti',
      title: 'Toplanti', at: DateTime(2026, 9, 16), tokens: ['date:carsamba']),
  CaptureCase('perşembe kuaför',
      title: 'Kuaför', at: DateTime(2026, 9, 17), tokens: ['date:perşembe']),
  CaptureCase('cuma sinema',
      title: 'Sinema', at: DateTime(2026, 9, 18), tokens: ['date:cuma']),
  CaptureCase('cumartesi pikniği',
      title: 'Pikniği', at: DateTime(2026, 9, 19), tokens: ['date:cumartesi']),
  CaptureCase('pazar kahvaltı',
      title: 'Kahvaltı', at: DateTime(2026, 9, 20), tokens: ['date:pazar']),
  CaptureCase('cumaya kadar raporu bitir',
      title: 'Raporu bitir',
      at: DateTime(2026, 9, 18),
      tokens: ['date:cumaya kadar']),
  CaptureCase('raporu cumaya yetiştir',
      title: 'Raporu yetiştir',
      at: DateTime(2026, 9, 18),
      tokens: ['date:cumaya']),
  CaptureCase('pazartesiye sunum hazırla',
      title: 'Sunum hazırla',
      at: DateTime(2026, 9, 14),
      tokens: ['date:pazartesiye']),
  CaptureCase('cuma günü sinema',
      title: 'Sinema', at: DateTime(2026, 9, 18), tokens: ['date:cuma günü']),
  CaptureCase('pazar günü annemi ara',
      title: 'Annemi ara',
      at: DateTime(2026, 9, 20),
      tokens: ['date:pazar günü']),
  CaptureCase('bu cuma kına gecesi',
      title: 'Kına gecesi',
      at: DateTime(2026, 9, 18),
      tokens: ['date:bu cuma']),
  CaptureCase("Cuma'ya kadar ödevi teslim et",
      title: 'Ödevi teslim et',
      at: DateTime(2026, 9, 18),
      tokens: ["date:Cuma'ya kadar"]),
  CaptureCase('pazara gidip domates al', title: 'Pazara gidip domates al'),
  CaptureCase('pazardan meyve al', title: 'Pazardan meyve al'),
  CaptureCase('şalı yıkamaya ver', title: 'Şalı yıkamaya ver'),
  CaptureCase('geçen cuma ödenen fatura', title: 'Geçen cuma ödenen fatura'),
  CaptureCase('hafta sonu pikniğe git',
      title: 'Pikniğe git',
      at: DateTime(2026, 9, 19),
      tokens: ['date:hafta sonu']),
  CaptureCase('bu hafta sonu temizlik',
      title: 'Temizlik',
      at: DateTime(2026, 9, 19),
      tokens: ['date:bu hafta sonu']),

  // ayın N'i
  CaptureCase("ayın 17'si kira",
      title: 'Kira', at: DateTime(2026, 9, 17), tokens: ["date:ayın 17'si"]),
  CaptureCase('ayın 17sinde kira öde',
      title: 'Kira öde',
      at: DateTime(2026, 9, 17),
      tokens: ['date:ayın 17sinde']),
  CaptureCase("ayın 5'i aidat",
      title: 'Aidat', at: DateTime(2026, 10, 5), tokens: ["date:ayın 5'i"]),
  CaptureCase("ayın 1'inde fatura",
      title: 'Fatura', at: DateTime(2026, 10, 1), tokens: ["date:ayın 1'inde"]),
  CaptureCase("ayın 13'ü randevu",
      title: 'Randevu', at: DateTime(2026, 9, 13), tokens: ["date:ayın 13'ü"]),
  CaptureCase("ayın 31'i rapor",
      title: 'Rapor', at: DateTime(2026, 10, 31), tokens: ["date:ayın 31'i"]),

  // 17 eylül
  CaptureCase('17 eylül doğum günü partisi',
      title: 'Doğum günü partisi',
      at: DateTime(2026, 9, 17),
      tokens: ['date:17 eylül']),
  CaptureCase("17 Eylül'de sınav",
      title: 'Sınav', at: DateTime(2026, 9, 17), tokens: ["date:17 Eylül'de"]),
  CaptureCase('5 mart vergi beyannamesi',
      title: 'Vergi beyannamesi',
      at: DateTime(2027, 3, 5),
      tokens: ['date:5 mart']),
  CaptureCase('12 eylül yıldönümü',
      title: 'Yıldönümü', at: DateTime(2027, 9, 12), tokens: ['date:12 eylül']),
  CaptureCase('13 eylül, bugün mü',
      title: 'Bugün mü', at: DateTime(2026, 9, 13), tokens: ['date:13 eylül']),
  CaptureCase('1 ocak 2027 yeni yıl',
      title: 'Yeni yıl',
      at: DateTime(2027, 1, 1),
      tokens: ['date:1 ocak 2027']),
  CaptureCase('17 eylül 2025 eski fatura',
      title: 'Eski fatura',
      at: DateTime(2025, 9, 17),
      past: true,
      tokens: ['date:17 eylül 2025']),
  CaptureCase('29 şubat doğum günü',
      title: 'Doğum günü',
      at: DateTime(2028, 2, 29),
      tokens: ['date:29 şubat']),
  CaptureCase('3 ARALIK konser',
      title: 'Konser', at: DateTime(2026, 12, 3), tokens: ['date:3 ARALIK']),
  CaptureCase('31 nisan toplantı', title: '31 nisan toplantı'),
  CaptureCase('17 nişan töreni', title: '17 nişan töreni'),

  // numeric
  CaptureCase('17.09 sunum',
      title: 'Sunum', at: DateTime(2026, 9, 17), tokens: ['date:17.09']),
  CaptureCase('17/09 sunum',
      title: 'Sunum', at: DateTime(2026, 9, 17), tokens: ['date:17/09']),
  CaptureCase('17.09.2027 sözleşme yenile',
      title: 'Sözleşme yenile',
      at: DateTime(2027, 9, 17),
      tokens: ['date:17.09.2027']),
  CaptureCase('01/10/26 fatura',
      title: 'Fatura', at: DateTime(2026, 10, 1), tokens: ['date:01/10/26']),
  CaptureCase('1.5 kilo elma', title: '1.5 kilo elma'),
  CaptureCase('12.08 ehliyet', // already past this year → next year
      title: 'Ehliyet',
      at: DateTime(2027, 8, 12),
      tokens: ['date:12.08']),

  // relative dates
  CaptureCase('3 gün sonra kontrol',
      title: 'Kontrol',
      at: DateTime(2026, 9, 16),
      tokens: ['date:3 gün sonra']),
  CaptureCase('2 hafta sonra aşı',
      title: 'Aşı', at: DateTime(2026, 9, 27), tokens: ['date:2 hafta sonra']),
  CaptureCase('1 ay sonra check-up',
      title: 'Check-up',
      at: DateTime(2026, 10, 13),
      tokens: ['date:1 ay sonra']),
  CaptureCase('iki gün sonra ara',
      title: 'Ara', at: DateTime(2026, 9, 15), tokens: ['date:iki gün sonra']),
];
