// Tables mix const-able and DateTime rows; keep them uniform.
// ignore_for_file: prefer_const_constructors

import 'capture_case.dart';

/// Repeats. `at` is the first occurrence.
/// Clock: Pazar 13 Eylül 2026 14:32.
final recurrenceCases = <CaptureCase>[
  // daily
  CaptureCase('her gün su iç',
      title: 'Su iç',
      at: DateTime(2026, 9, 13),
      rec: daily(),
      tokens: ['recurrence:her gün']),
  CaptureCase('hergün su iç',
      title: 'Su iç',
      at: DateTime(2026, 9, 13),
      rec: daily(),
      tokens: ['recurrence:hergün']),
  CaptureCase('HER GÜN su iç',
      title: 'Su iç',
      at: DateTime(2026, 9, 13),
      rec: daily(),
      tokens: ['recurrence:HER GÜN']),
  CaptureCase("her gün 9'da vitamin",
      title: 'Vitamin',
      at: DateTime(2026, 9, 14, 9),
      rec: daily(),
      tokens: ['recurrence:her gün', "time:9'da"]),
  CaptureCase('her gün 18:00 yürüyüş',
      title: 'Yürüyüş',
      at: DateTime(2026, 9, 13, 18),
      rec: daily(),
      tokens: ['recurrence:her gün', 'time:18:00']),
  CaptureCase('her sabah vitamin',
      title: 'Vitamin',
      at: DateTime(2026, 9, 14, 9),
      rec: daily(),
      tokens: ['recurrence:her sabah']),
  CaptureCase("her sabah 7'de koşu",
      title: 'Koşu',
      at: DateTime(2026, 9, 14, 7),
      rec: daily(),
      tokens: ['recurrence:her sabah', "time:7'de"]),
  CaptureCase('her akşam diş ipi',
      title: 'Diş ipi',
      at: DateTime(2026, 9, 13, 20),
      rec: daily(),
      tokens: ['recurrence:her akşam']),
  CaptureCase("her akşam 9'da ilaç",
      title: 'İlaç',
      at: DateTime(2026, 9, 13, 21),
      rec: daily(),
      tokens: ['recurrence:her akşam', "time:9'da"]),
  CaptureCase('her gece kitap oku',
      title: 'Kitap oku',
      at: DateTime(2026, 9, 13, 22),
      rec: daily(),
      tokens: ['recurrence:her gece']),
  CaptureCase('her öğlen yürüyüş',
      title: 'Yürüyüş',
      at: DateTime(2026, 9, 14, 12),
      rec: daily(),
      tokens: ['recurrence:her öğlen']),
  CaptureCase('sabahları vitamin',
      title: 'Vitamin',
      at: DateTime(2026, 9, 14, 9),
      rec: daily(),
      tokens: ['recurrence:sabahları']),
  CaptureCase("akşamları 9'da ilaç",
      title: 'İlaç',
      at: DateTime(2026, 9, 13, 21),
      rec: daily(),
      tokens: ['recurrence:akşamları', "time:9'da"]),
  CaptureCase('geceleri cilt bakımı',
      title: 'Cilt bakımı',
      at: DateTime(2026, 9, 13, 22),
      rec: daily(),
      tokens: ['recurrence:geceleri']),
  CaptureCase('yarın her gün koşu',
      title: 'Koşu',
      at: DateTime(2026, 9, 14),
      rec: daily(),
      tokens: ['date:yarın', 'recurrence:her gün']),
  CaptureCase('1 günde bir su',
      title: 'Su',
      at: DateTime(2026, 9, 13),
      rec: daily(),
      tokens: ['recurrence:1 günde bir']),

  // weekly
  CaptureCase('her hafta çarşaf değiştir',
      title: 'Çarşaf değiştir',
      at: DateTime(2026, 9, 13),
      rec: weekly([7]),
      tokens: ['recurrence:her hafta']),
  CaptureCase('her hafta 10:00 rapor',
      title: 'Rapor',
      at: DateTime(2026, 9, 20, 10),
      rec: weekly([7]),
      tokens: ['recurrence:her hafta', 'time:10:00']),
  CaptureCase('her pazartesi toplantı',
      title: 'Toplantı',
      at: DateTime(2026, 9, 14),
      rec: weekly([1]),
      tokens: ['recurrence:her pazartesi']),
  CaptureCase('her cuma 18:00 halı saha',
      title: 'Halı saha',
      at: DateTime(2026, 9, 18, 18),
      rec: weekly([5]),
      tokens: ['recurrence:her cuma', 'time:18:00']),
  CaptureCase('her pazar kahvaltı',
      title: 'Kahvaltı',
      at: DateTime(2026, 9, 13),
      rec: weekly([7]),
      tokens: ['recurrence:her pazar']),
  CaptureCase('her pazar 10:00 kahvaltı',
      title: 'Kahvaltı',
      at: DateTime(2026, 9, 20, 10),
      rec: weekly([7]),
      tokens: ['recurrence:her pazar', 'time:10:00']),
  CaptureCase('her pazartesi ve cuma spor',
      title: 'Spor',
      at: DateTime(2026, 9, 14),
      rec: weekly([1, 5]),
      tokens: ['recurrence:her pazartesi ve cuma']),
  CaptureCase('her pazartesi, çarşamba ve cuma spor',
      title: 'Spor',
      at: DateTime(2026, 9, 14),
      rec: weekly([1, 3, 5]),
      tokens: ['recurrence:her pazartesi, çarşamba ve cuma']),
  CaptureCase('her salı ile perşembe kurs',
      title: 'Kurs',
      at: DateTime(2026, 9, 15),
      rec: weekly([2, 4]),
      tokens: ['recurrence:her salı ile perşembe']),
  CaptureCase('her cuma günü namaz',
      title: 'Namaz',
      at: DateTime(2026, 9, 18),
      rec: weekly([5]),
      tokens: ['recurrence:her cuma günü']),
  CaptureCase('her cuma akşamı sinema',
      title: 'Sinema',
      at: DateTime(2026, 9, 18, 20),
      rec: weekly([5]),
      tokens: ['recurrence:her cuma', 'time:akşamı']),
  CaptureCase('her pazartesi ve ekmek al',
      title: 'Ekmek al',
      at: DateTime(2026, 9, 14),
      rec: weekly([1]),
      tokens: ['recurrence:her pazartesi']),
  CaptureCase('hafta içi 8:00 servis',
      title: 'Servis',
      at: DateTime(2026, 9, 14, 8),
      rec: weekly([1, 2, 3, 4, 5]),
      tokens: ['recurrence:hafta içi', 'time:8:00']),
  CaptureCase('hafta içleri spor',
      title: 'Spor',
      at: DateTime(2026, 9, 14),
      rec: weekly([1, 2, 3, 4, 5]),
      tokens: ['recurrence:hafta içleri']),
  CaptureCase('her hafta içi rapor',
      title: 'Rapor',
      at: DateTime(2026, 9, 14),
      rec: weekly([1, 2, 3, 4, 5]),
      tokens: ['recurrence:her hafta içi']),
  CaptureCase('haftaiçi rapor',
      title: 'Rapor',
      at: DateTime(2026, 9, 14),
      rec: weekly([1, 2, 3, 4, 5]),
      tokens: ['recurrence:haftaiçi']),
  CaptureCase('hafta sonları kahvaltı',
      title: 'Kahvaltı',
      at: DateTime(2026, 9, 13),
      rec: weekly([6, 7]),
      tokens: ['recurrence:hafta sonları']),
  CaptureCase('her hafta sonu temizlik',
      title: 'Temizlik',
      at: DateTime(2026, 9, 13),
      rec: weekly([6, 7]),
      tokens: ['recurrence:her hafta sonu']),
  CaptureCase('cumaları yüzme',
      title: 'Yüzme',
      at: DateTime(2026, 9, 18),
      rec: weekly([5]),
      tokens: ['recurrence:cumaları']),
  CaptureCase('pazartesileri ve perşembeleri kurs',
      title: 'Kurs',
      at: DateTime(2026, 9, 14),
      rec: weekly([1, 4]),
      tokens: ['recurrence:pazartesileri ve perşembeleri']),
  CaptureCase('pazarları kapalı', title: 'Pazarları kapalı'),
  CaptureCase('2 haftada bir kuaför',
      title: 'Kuaför',
      at: DateTime(2026, 9, 13),
      rec: weekly([7], interval: 2),
      tokens: ['recurrence:2 haftada bir']),
  CaptureCase('iki haftada bir kuaför',
      title: 'Kuaför',
      at: DateTime(2026, 9, 13),
      rec: weekly([7], interval: 2),
      tokens: ['recurrence:iki haftada bir']),

  // every N days
  CaptureCase('3 günde bir sula',
      title: 'Sula',
      at: DateTime(2026, 9, 13),
      rec: everyDays(3),
      tokens: ['recurrence:3 günde bir']),
  CaptureCase('üç günde bir sula',
      title: 'Sula',
      at: DateTime(2026, 9, 13),
      rec: everyDays(3),
      tokens: ['recurrence:üç günde bir']),
  CaptureCase('gün aşırı sula',
      title: 'Sula',
      at: DateTime(2026, 9, 13),
      rec: everyDays(2),
      tokens: ['recurrence:gün aşırı']),
  CaptureCase('günaşırı sula',
      title: 'Sula',
      at: DateTime(2026, 9, 13),
      rec: everyDays(2),
      tokens: ['recurrence:günaşırı']),
  CaptureCase("5 günde bir 10'da filtre",
      title: 'Filtre',
      at: DateTime(2026, 9, 14, 10),
      rec: everyDays(5),
      tokens: ['recurrence:5 günde bir', "time:10'da"]),

  // monthly
  CaptureCase('her ay kira öde',
      title: 'Kira öde',
      at: DateTime(2026, 9, 13),
      rec: monthly(13),
      tokens: ['recurrence:her ay']),
  CaptureCase("her ayın 17'si kira",
      title: 'Kira',
      at: DateTime(2026, 9, 17),
      rec: monthly(17),
      tokens: ["recurrence:her ayın 17'si"]),
  CaptureCase("her ayın 1'i fatura",
      title: 'Fatura',
      at: DateTime(2026, 10, 1),
      rec: monthly(1),
      tokens: ["recurrence:her ayın 1'i"]),
  CaptureCase("her ay 15'inde maaş",
      title: 'Maaş',
      at: DateTime(2026, 9, 15),
      rec: monthly(15),
      tokens: ["recurrence:her ay 15'inde"]),
  CaptureCase("her ayın 31'i rapor",
      title: 'Rapor',
      at: DateTime(2026, 10, 31),
      rec: monthly(31),
      tokens: ["recurrence:her ayın 31'i"]),
  CaptureCase("her ayın 13'ü 10:00 aidat",
      title: 'Aidat',
      at: DateTime(2026, 10, 13, 10),
      rec: monthly(13),
      tokens: ["recurrence:her ayın 13'ü", 'time:10:00']),
  CaptureCase('3 ayda bir kontrol',
      title: 'Kontrol',
      at: DateTime(2026, 9, 13),
      rec: monthly(13, interval: 3),
      tokens: ['recurrence:3 ayda bir']),

  // yearly
  CaptureCase('her yıl vergi',
      title: 'Vergi',
      at: DateTime(2026, 9, 13),
      rec: yearly(),
      tokens: ['recurrence:her yıl']),
  CaptureCase('her sene sigorta yenile',
      title: 'Sigorta yenile',
      at: DateTime(2026, 9, 13),
      rec: yearly(),
      tokens: ['recurrence:her sene']),
  CaptureCase('HER YIL check-up',
      title: 'Check-up',
      at: DateTime(2026, 9, 13),
      rec: yearly(),
      tokens: ['recurrence:HER YIL']),
  CaptureCase('yıllık kontrol',
      title: 'Kontrol',
      at: DateTime(2026, 9, 13),
      rec: yearly(),
      tokens: ['recurrence:yıllık']),
  CaptureCase('senelik muayene',
      title: 'Muayene',
      at: DateTime(2026, 9, 13),
      rec: yearly(),
      tokens: ['recurrence:senelik']),
  CaptureCase('her yıl 18:00 yoklama',
      title: 'Yoklama',
      at: DateTime(2026, 9, 13, 18),
      rec: yearly(),
      tokens: ['recurrence:her yıl', 'time:18:00']),
  CaptureCase('1 yılda bir ehliyet kontrolü',
      title: 'Ehliyet kontrolü',
      at: DateTime(2026, 9, 13),
      rec: yearly(),
      tokens: ['recurrence:1 yılda bir']),
  CaptureCase('2 yılda bir pasaport yenile',
      title: 'Pasaport yenile',
      at: DateTime(2026, 9, 13),
      rec: yearly(interval: 2),
      tokens: ['recurrence:2 yılda bir']),
  CaptureCase('iki senede bir diş temizliği',
      title: 'Diş temizliği',
      at: DateTime(2026, 9, 13),
      rec: yearly(interval: 2),
      tokens: ['recurrence:iki senede bir']),
  CaptureCase('5 senede bir kimlik yenile',
      title: 'Kimlik yenile',
      at: DateTime(2026, 9, 13),
      rec: yearly(interval: 5),
      tokens: ['recurrence:5 senede bir']),

  // not supported / conflicts
  // "yıllık" / "senelik" in front of a noun is an adjective, not a repeat.
  CaptureCase('yıllık rapor hazırla', title: 'Yıllık rapor hazırla'),
  CaptureCase('yıllık izin planla', title: 'Yıllık izin planla'),
  CaptureCase('senelik abonelik yenile', title: 'Senelik abonelik yenile'),
  CaptureCase('her şey yolunda', title: 'Her şey yolunda'),
  CaptureCase('her gün, her hafta',
      title: 'Her hafta',
      at: DateTime(2026, 9, 13),
      rec: daily(),
      tokens: ['recurrence:her gün']),
];
