import 'capture_case.dart';

/// Tag examples: `#kategori`, `!` priority, `@yer`.
const tagCases = <CaptureCase>[
  CaptureCase('ekmek al #market',
      title: 'Ekmek al',
      tag: 'market',
      categoryId: 'market',
      tokens: ['category:#market']),
  CaptureCase('#MARKET ekmek',
      title: 'Ekmek',
      tag: 'MARKET',
      categoryId: 'market',
      tokens: ['category:#MARKET']),
  CaptureCase('raporu gönder #iş',
      title: 'Raporu gönder',
      tag: 'iş',
      categoryId: 'work',
      tokens: ['category:#iş']),
  CaptureCase('raporu gönder #is',
      title: 'Raporu gönder',
      tag: 'is',
      categoryId: 'work',
      tokens: ['category:#is']),
  CaptureCase('raporu gönder #İŞ',
      title: 'Raporu gönder',
      tag: 'İŞ',
      categoryId: 'work',
      tokens: ['category:#İŞ']),
  CaptureCase('raporu gönder #IS',
      title: 'Raporu gönder',
      tag: 'IS',
      categoryId: 'work',
      tokens: ['category:#IS']),
  CaptureCase('vitamin iç #sağlık',
      title: 'Vitamin iç',
      tag: 'sağlık',
      categoryId: 'health',
      tokens: ['category:#sağlık']),
  CaptureCase('vitamin iç #saglik',
      title: 'Vitamin iç',
      tag: 'saglik',
      categoryId: 'health',
      tokens: ['category:#saglik']),
  CaptureCase('vitamin iç #SAĞLIK',
      title: 'Vitamin iç',
      tag: 'SAĞLIK',
      categoryId: 'health',
      tokens: ['category:#SAĞLIK']),
  CaptureCase('#ev çamaşırları as',
      title: 'Çamaşırları as',
      tag: 'ev',
      categoryId: 'home',
      tokens: ['category:#ev']),
  CaptureCase('bulaşık #ev_isleri',
      title: 'Bulaşık',
      tag: 'ev_isleri',
      categoryId: 'home',
      tokens: ['category:#ev_isleri']),
  CaptureCase('fatura öde #günlük',
      title: 'Fatura öde',
      tag: 'günlük',
      categoryId: 'errands',
      tokens: ['category:#günlük']),
  CaptureCase('fatura öde #gunluk',
      title: 'Fatura öde',
      tag: 'gunluk',
      categoryId: 'errands',
      tokens: ['category:#gunluk']),
  CaptureCase('not al #diğer',
      title: 'Not al',
      tag: 'diğer',
      categoryId: 'other',
      tokens: ['category:#diğer']),
  CaptureCase('deterjan #markt',
      title: 'Deterjan',
      tag: 'markt',
      categoryId: 'market',
      tokens: ['category:#markt']),
  CaptureCase('kitap oku #hobi',
      title: 'Kitap oku', tag: 'hobi', tokens: ['category:#hobi']),
  CaptureCase('İstanbul biletleri #seyahat',
      title: 'İstanbul biletleri',
      tag: 'seyahat',
      tokens: ['category:#seyahat']),
  CaptureCase('#market #iş ekmek',
      title: '#iş ekmek',
      tag: 'market',
      categoryId: 'market',
      tokens: ['category:#market']),
  CaptureCase('faturayı öde !',
      title: 'Faturayı öde', priority: 1, tokens: ['priority:!']),
  CaptureCase('faturayı öde !!',
      title: 'Faturayı öde', priority: 2, tokens: ['priority:!!']),
  CaptureCase('!!! faturayı öde',
      title: 'Faturayı öde', priority: 3, tokens: ['priority:!!!']),
  CaptureCase('acil! faturayı öde', title: 'Acil! faturayı öde'),
  CaptureCase('faturayı öde !!!!', title: 'Faturayı öde !!!!'),
  CaptureCase('ışıkları kapat @ev',
      title: 'Işıkları kapat', place: 'ev', tokens: ['place:@ev']),
  CaptureCase('@ofis çıktıları al',
      title: 'Çıktıları al', place: 'ofis', tokens: ['place:@ofis']),
  CaptureCase('mail at ali@ornek.com', title: 'Mail at ali@ornek.com'),
  CaptureCase('C# kursuna yazıl', title: 'C# kursuna yazıl'),
  CaptureCase('ilaç al #sağlık !! @ev',
      title: 'İlaç al',
      tag: 'sağlık',
      categoryId: 'health',
      priority: 2,
      place: 'ev',
      tokens: ['category:#sağlık', 'priority:!!', 'place:@ev']),
];
