// Tables mix const-able and DateTime rows; keep them uniform.
// ignore_for_file: prefer_const_constructors

import 'capture_case.dart';

/// Clock times, day parts, date + time and relative times.
/// Clock: Pazar 13 Eylül 2026 14:32.
final timeCases = <CaptureCase>[
  // clock
  CaptureCase('toplantı 18:00',
      title: 'Toplantı',
      at: DateTime(2026, 9, 13, 18),
      tokens: ['time:18:00']),
  CaptureCase('18:00 toplantı',
      title: 'Toplantı',
      at: DateTime(2026, 9, 13, 18),
      tokens: ['time:18:00']),
  CaptureCase('saat 18:30 toplantı',
      title: 'Toplantı',
      at: DateTime(2026, 9, 13, 18, 30),
      tokens: ['time:saat 18:30']),
  CaptureCase("18:00'de toplantı",
      title: 'Toplantı',
      at: DateTime(2026, 9, 13, 18),
      tokens: ["time:18:00'de"]),
  CaptureCase('18.30 yoga',
      title: 'Yoga',
      at: DateTime(2026, 9, 13, 18, 30),
      tokens: ['time:18.30']),
  CaptureCase("18.30'da yoga",
      title: 'Yoga',
      at: DateTime(2026, 9, 13, 18, 30),
      tokens: ["time:18.30'da"]),
  CaptureCase("17.09'da çay",
      title: 'Çay',
      at: DateTime(2026, 9, 13, 17, 9),
      tokens: ["time:17.09'da"]),
  CaptureCase("9'da dişçi",
      title: 'Dişçi',
      at: DateTime(2026, 9, 14, 9),
      tokens: ["time:9'da"]),
  CaptureCase('9da dişçi',
      title: 'Dişçi', at: DateTime(2026, 9, 14, 9), tokens: ['time:9da']),
  CaptureCase('9’da dişçi',
      title: 'Dişçi', at: DateTime(2026, 9, 14, 9), tokens: ['time:9’da']),
  CaptureCase("15'te toplantı",
      title: 'Toplantı',
      at: DateTime(2026, 9, 13, 15),
      tokens: ["time:15'te"]),
  CaptureCase('saat 9 dişçi',
      title: 'Dişçi',
      at: DateTime(2026, 9, 14, 9),
      tokens: ['time:saat 9']),
  CaptureCase("saat 9'da dişçi",
      title: 'Dişçi',
      at: DateTime(2026, 9, 14, 9),
      tokens: ["time:saat 9'da"]),
  CaptureCase('9 buçukta toplantı',
      title: 'Toplantı',
      at: DateTime(2026, 9, 14, 9, 30),
      tokens: ['time:9 buçukta']),
  CaptureCase('saat 3 buçuk çay',
      title: 'Çay',
      at: DateTime(2026, 9, 14, 3, 30),
      tokens: ['time:saat 3 buçuk']),
  CaptureCase('8:15 servis',
      title: 'Servis',
      at: DateTime(2026, 9, 14, 8, 15),
      tokens: ['time:8:15']),
  CaptureCase('14:32 hemen şimdi',
      title: 'Hemen şimdi',
      at: DateTime(2026, 9, 14, 14, 32),
      tokens: ['time:14:32']),
  CaptureCase("18:00'e kadar teslim",
      title: 'Teslim',
      at: DateTime(2026, 9, 13, 18),
      tokens: ["time:18:00'e kadar"]),

  // date + time
  CaptureCase("bugün 9'da toplantı",
      title: 'Toplantı',
      at: DateTime(2026, 9, 13, 9),
      past: true,
      tokens: ['date:bugün', "time:9'da"]),
  CaptureCase("bugün 18'de maç",
      title: 'Maç',
      at: DateTime(2026, 9, 13, 18),
      tokens: ['date:bugün', "time:18'de"]),
  CaptureCase('yarın 18:00 ekmek al',
      title: 'Ekmek al',
      at: DateTime(2026, 9, 14, 18),
      tokens: ['date:yarın', 'time:18:00']),
  CaptureCase("yarın akşam 8'de yemek",
      title: 'Yemek',
      at: DateTime(2026, 9, 14, 20),
      tokens: ['date:yarın', "time:akşam 8'de"]),
  CaptureCase('pazar 18:00 maç',
      title: 'Maç',
      at: DateTime(2026, 9, 13, 18),
      tokens: ['date:pazar', 'time:18:00']),
  CaptureCase('pazar 10:00 kahvaltı',
      title: 'Kahvaltı',
      at: DateTime(2026, 9, 20, 10),
      tokens: ['date:pazar', 'time:10:00']),
  CaptureCase('13 eylül 10:00 randevu',
      title: 'Randevu',
      at: DateTime(2026, 9, 13, 10),
      past: true,
      tokens: ['date:13 eylül', 'time:10:00']),
  CaptureCase('17 eylül 10:30 dişçi',
      title: 'Dişçi',
      at: DateTime(2026, 9, 17, 10, 30),
      tokens: ['date:17 eylül', 'time:10:30']),
  CaptureCase('ayın 20si saat 15:00 kira',
      title: 'Kira',
      at: DateTime(2026, 9, 20, 15),
      tokens: ['date:ayın 20si', 'time:saat 15:00']),
  CaptureCase("cuma günü saat 18:00'de maç",
      title: 'Maç',
      at: DateTime(2026, 9, 18, 18),
      tokens: ['date:cuma günü', "time:saat 18:00'de"]),
  CaptureCase('haftaya cuma 14:00 sunum',
      title: 'Sunum',
      at: DateTime(2026, 9, 25, 14),
      tokens: ['date:haftaya cuma', 'time:14:00']),
  CaptureCase('cuma akşamı sinema',
      title: 'Sinema',
      at: DateTime(2026, 9, 18, 20),
      tokens: ['date:cuma', 'time:akşamı']),
  CaptureCase('cuma akşam sinema',
      title: 'Sinema',
      at: DateTime(2026, 9, 18, 20),
      tokens: ['date:cuma', 'time:akşam']),
  CaptureCase('17.09 18:00 sunum',
      title: 'Sunum',
      at: DateTime(2026, 9, 17, 18),
      tokens: ['date:17.09', 'time:18:00']),

  // day parts
  CaptureCase('akşam ekmek al',
      title: 'Ekmek al',
      at: DateTime(2026, 9, 13, 20),
      tokens: ['time:akşam']),
  CaptureCase('ekmek al akşam',
      title: 'Ekmek al',
      at: DateTime(2026, 9, 13, 20),
      tokens: ['time:akşam']),
  CaptureCase('annemi akşam ara',
      title: 'Annemi ara',
      at: DateTime(2026, 9, 13, 20),
      tokens: ['time:akşam']),
  CaptureCase('AKŞAM ekmek al',
      title: 'Ekmek al',
      at: DateTime(2026, 9, 13, 20),
      tokens: ['time:AKŞAM']),
  CaptureCase('sabah vitamin iç',
      title: 'Vitamin iç',
      at: DateTime(2026, 9, 14, 9),
      tokens: ['time:sabah']),
  CaptureCase('sabahleyin ilaç',
      title: 'İlaç',
      at: DateTime(2026, 9, 14, 9),
      tokens: ['time:sabahleyin']),
  CaptureCase('öğlen toplantı',
      title: 'Toplantı',
      at: DateTime(2026, 9, 14, 12),
      tokens: ['time:öğlen']),
  CaptureCase('oglen toplanti',
      title: 'Toplanti',
      at: DateTime(2026, 9, 14, 12),
      tokens: ['time:oglen']),
  CaptureCase('gece çöpü çıkar',
      title: 'Çöpü çıkar',
      at: DateTime(2026, 9, 13, 22),
      tokens: ['time:gece']),
  CaptureCase('akşama ekmek al',
      title: 'Ekmek al',
      at: DateTime(2026, 9, 13, 20),
      tokens: ['time:akşama']),
  CaptureCase('akşama kadar bitir',
      title: 'Bitir',
      at: DateTime(2026, 9, 13, 20),
      tokens: ['time:akşama kadar']),
  CaptureCase('öğleden sonra kargo',
      title: 'Kargo',
      at: DateTime(2026, 9, 13, 15),
      tokens: ['time:öğleden sonra']),
  CaptureCase("akşam 8'de sinema",
      title: 'Sinema',
      at: DateTime(2026, 9, 13, 20),
      tokens: ["time:akşam 8'de"]),
  CaptureCase("akşam saat 8'de sinema",
      title: 'Sinema',
      at: DateTime(2026, 9, 13, 20),
      tokens: ["time:akşam saat 8'de"]),
  CaptureCase('akşam 8 buçukta sinema',
      title: 'Sinema',
      at: DateTime(2026, 9, 13, 20, 30),
      tokens: ['time:akşam 8 buçukta']),
  CaptureCase("sabah 7'de koşu",
      title: 'Koşu',
      at: DateTime(2026, 9, 14, 7),
      tokens: ["time:sabah 7'de"]),
  CaptureCase("gece 11'de ilaç",
      title: 'İlaç',
      at: DateTime(2026, 9, 13, 23),
      tokens: ["time:gece 11'de"]),
  CaptureCase("gece 2'de uyan",
      title: 'Uyan',
      at: DateTime(2026, 9, 14, 2),
      tokens: ["time:gece 2'de"]),
  CaptureCase("öğlen 1'de toplantı",
      title: 'Toplantı',
      at: DateTime(2026, 9, 13, 13),
      tokens: ["time:öğlen 1'de"]),
  CaptureCase("öğleden sonra 3'te toplantı",
      title: 'Toplantı',
      at: DateTime(2026, 9, 13, 15),
      tokens: ["time:öğleden sonra 3'te"]),
  CaptureCase('bu akşam sinema',
      title: 'Sinema',
      at: DateTime(2026, 9, 13, 20),
      tokens: ['time:bu akşam']),
  CaptureCase('bu sabah ilaç',
      title: 'İlaç',
      at: DateTime(2026, 9, 13, 9),
      past: true,
      tokens: ['time:bu sabah']),
  CaptureCase("bu akşam 9'da maç",
      title: 'Maç',
      at: DateTime(2026, 9, 13, 21),
      tokens: ["time:bu akşam 9'da"]),

  // not temporal
  CaptureCase('akşamki toplantı notları', title: 'Akşamki toplantı notları'),
  CaptureCase('akşam yemeği hazırla', title: 'Akşam yemeği hazırla'),
  CaptureCase('öğle yemeği siparişi', title: 'Öğle yemeği siparişi'),
  CaptureCase('öğle arası bankaya uğra', title: 'Öğle arası bankaya uğra'),
  CaptureCase('gece kremi al', title: 'Gece kremi al'),
  CaptureCase('sabah sporu programı', title: 'Sabah sporu programı'),
  CaptureCase('bir akşam sinemaya gidelim',
      title: 'Bir akşam sinemaya gidelim'),
  CaptureCase('dün akşam kaybolan anahtar',
      title: 'Dün akşam kaybolan anahtar'),
  CaptureCase('akşamın tadını çıkar', title: 'Akşamın tadını çıkar'),
  CaptureCase('kına gecesi hazırlığı', title: 'Kına gecesi hazırlığı'),
  CaptureCase("karışımı 3'te bir oranında sulandır",
      title: "Karışımı 3'te bir oranında sulandır"),
  CaptureCase('ekmek 1.50 tl', title: 'Ekmek 1.50 tl'),
  CaptureCase('1 buçuk kilo elma', title: '1 buçuk kilo elma'),
  CaptureCase('saat kulesini ziyaret et', title: 'Saat kulesini ziyaret et'),
  CaptureCase('25:00 hata', title: '25:00 hata'),

  // relative times
  CaptureCase('2 saat sonra fırını kapat',
      title: 'Fırını kapat',
      at: DateTime(2026, 9, 13, 16, 32),
      tokens: ['time:2 saat sonra']),
  CaptureCase('yarım saat sonra çayı demle',
      title: 'Çayı demle',
      at: DateTime(2026, 9, 13, 15, 2),
      tokens: ['time:yarım saat sonra']),
  CaptureCase('10 dk sonra ara',
      title: 'Ara',
      at: DateTime(2026, 9, 13, 14, 42),
      tokens: ['time:10 dk sonra']),
  CaptureCase('45 dakika sonra çık',
      title: 'Çık',
      at: DateTime(2026, 9, 13, 15, 17),
      tokens: ['time:45 dakika sonra']),
  CaptureCase('bir saat sonra ütüyü kapat',
      title: 'Ütüyü kapat',
      at: DateTime(2026, 9, 13, 15, 32),
      tokens: ['time:bir saat sonra']),
];
